"use client";

import { Download, Shield, Trash2 } from "lucide-react";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h2 className="font-[family-name:var(--font-display)] text-ink text-2xl mb-1">Privacy & Data</h2>
        <p className="text-ink-muted text-sm">How we handle your data and what you control.</p>
      </div>

      {/* How we use your data */}
      <div className="bg-white rounded-3xl border border-ink/10 shadow-card p-6">
        <div className="flex items-center gap-3 mb-5">
          <div className="w-10 h-10 rounded-2xl bg-brand/10 flex items-center justify-center">
            <Shield className="w-5 h-5 text-brand" />
          </div>
          <h3 className="font-[family-name:var(--font-display)] text-ink text-lg">Our Privacy Commitment</h3>
        </div>
        <ul className="space-y-4">
          {[
            {
              icon: "📸",
              title: "Photos deleted after avatar generation",
              body: "Any photo you upload for avatar creation is processed temporarily to create an illustrated avatar. The original photo is deleted immediately after — we never store it.",
            },
            {
              icon: "🤖",
              title: "We never train AI on your photos",
              body: "Your child's photos and generated content are never used to train AI models. They are used solely to generate your specific stories.",
            },
            {
              icon: "🎨",
              title: "Generated assets belong to you",
              body: "All story pages, covers, and avatars generated by HeroKids Universe are yours to download, print, and keep. We don't claim ownership.",
            },
            {
              icon: "🔒",
              title: "Data is never sold",
              body: "We do not sell, rent, or share your personal information with advertisers or third parties. Your data exists solely to power your HeroKids Universe experience.",
            },
            {
              icon: "👶",
              title: "Child data protection",
              body: "We are COPPA-compliant. We collect only what is necessary (child's name, age, gender) to personalise stories and never use it for advertising purposes.",
            },
          ].map((item) => (
            <li key={item.title} className="flex gap-4">
              <span className="text-2xl mt-0.5 shrink-0">{item.icon}</span>
              <div>
                <p className="text-sm font-semibold text-ink mb-0.5">{item.title}</p>
                <p className="text-xs text-ink-muted leading-relaxed">{item.body}</p>
              </div>
            </li>
          ))}
        </ul>
      </div>

      {/* Data actions */}
      <div className="bg-white rounded-3xl border border-ink/10 shadow-card p-6">
        <h3 className="font-[family-name:var(--font-display)] text-ink text-lg mb-5">Your Data Rights</h3>
        <div className="space-y-4">

          {/* Download data */}
          <div className="flex items-start justify-between gap-4 py-3 border-b border-ink/6">
            <div className="flex items-start gap-3">
              <Download className="w-5 h-5 text-brand mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-ink">Download My Data</p>
                <p className="text-xs text-ink-muted mt-0.5">Request a copy of all data we hold about you — profile, orders, stories, characters.</p>
              </div>
            </div>
            <button type="button"
              className="shrink-0 text-xs font-semibold text-brand border border-brand/30 px-4 py-2 rounded-full hover:bg-brand/5 transition opacity-60 cursor-not-allowed"
              title="Coming soon">
              Coming Soon
            </button>
          </div>

          {/* Delete character */}
          <div className="flex items-start justify-between gap-4 py-3 border-b border-ink/6">
            <div className="flex items-start gap-3">
              <Trash2 className="w-5 h-5 text-orange-500 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-ink">Manage Characters</p>
                <p className="text-xs text-ink-muted mt-0.5">Delete individual characters and their associated avatars from your account.</p>
              </div>
            </div>
            <Link href="/account/characters"
              className="shrink-0 text-xs font-semibold text-brand border border-brand/30 px-4 py-2 rounded-full hover:bg-brand/5 transition">
              Manage →
            </Link>
          </div>

          {/* Delete universe */}
          <div className="flex items-start justify-between gap-4 py-3 border-b border-ink/6">
            <div className="flex items-start gap-3">
              <Trash2 className="w-5 h-5 text-orange-500 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-ink">Manage Universes</p>
                <p className="text-xs text-ink-muted mt-0.5">View or manage your story universes and the data they contain.</p>
              </div>
            </div>
            <Link href="/account/universes"
              className="shrink-0 text-xs font-semibold text-brand border border-brand/30 px-4 py-2 rounded-full hover:bg-brand/5 transition">
              Manage →
            </Link>
          </div>

          {/* Delete account */}
          <div className="flex items-start justify-between gap-4 py-3">
            <div className="flex items-start gap-3">
              <Trash2 className="w-5 h-5 text-red-500 mt-0.5 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-red-600">Request Account Deletion</p>
                <p className="text-xs text-ink-muted mt-0.5">
                  To delete your account and all associated data, email us at{" "}
                  <a href="mailto:privacy@herokidsuniverse.com" className="text-brand underline">
                    privacy@herokidsuniverse.com
                  </a>
                  . We will process your request within 30 days.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <p className="text-ink-muted text-xs leading-relaxed">
        For questions about privacy, contact us at{" "}
        <a href="mailto:privacy@herokidsuniverse.com" className="text-brand underline">
          privacy@herokidsuniverse.com
        </a>
        . We are committed to protecting your family&apos;s privacy.
      </p>
    </div>
  );
}
